#!/bin/bash

#To use this script, open the Terminal app and go to the directry
#where this script is located and excecute the following commands:
	# chmod u+x PleaseSleep

	# ./PleaseSleep install
	# -------- OR ---------
	# ./PleaseSleep remove

# Get the argument
set -e
ARG=$1

# quit if any command fails
if [ -z "$1" ] ; then
	echo "Error: No parameter. Use 'PleaseSleep install' or 'PleaseSleep remove'."
	exit 1


# REMOVE EVERYTHING
elif [ "$ARG" == "remove" ] || [ "$ARG" == "uninstall" ]
then
	echo -e "\n\n\nREMOVING PleaseSleep with sleepwatcher 2.2\nThis will remove all PleaseSleep AND all Sleepwatcher files.\nThis also includes the sleep and wake scripts.\n\nAre you sure you want to continue?\nPress Enter to continue or Crtl+c to quit"
	read
	echo -e "-------------------------------------------------------------------\n"

	echo "Unloading the LaunchAgent..."
	launchctl unload ~/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist &> /dev/null
	echo -e "Done.\n(Press ENTER key to continue.)"
	read

	echo "\nRemoving sleep and wake scripts ..."
	rm ~/.sleep &> /dev/null
	rm ~/.wakeup &> /dev/null
	echo -e "Done.\n(Press ENTER key to continue.)"
	read

	echo -e "\nRemoving Sleepwatcher 2.2 and all the files ..."
	sudo rm -r /usr/local/Cellar/sleepwatcher &> /dev/null
	sudo rm -r /usr/local/etc/sleepwatcher &> /dev/null
	sudo rm ~/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist &> /dev/null
  	#sudo rm /usr/local/share/man/man8/sleepwatcher.8 &> /dev/null
  	#sudo rm /etc/rc.sleep &> /dev/null
  	#sudo rm /etc/rc.wakeup &> /dev/null
  	#sudo rm -r /Library/StartupItems/SleepWatcher &> /dev/null
	sudo rm /usr/local/sbin/sleepwatcher &> /dev/null

	echo -e "Done.\n(Press ENTER key to continue.)"
	read
	echo -e "\n-------------------------------------------------------------------\n\nPleaseSleep and Sleepwatcher 2.2 are successfully removed from your lovely Mac!!\n\n\n"

# INSTALL EVERYTHING
elif [ "$1" == "install" ]
then
	echo -e "\n\n\nINSTALLING PleaseSleep with sleepwatcher 2.2\n\nAre you sure you want to continue?\nPress Enter to continue or Crtl+c to quit"
	read
	echo "-------------------------------------------------------------------\n"

	echo "Gaining permissions for /usr/local ..."
	# source: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md
	sudo chown -R $(whoami):admin /usr/local
	echo -e "Done.\n(Press ENTER key to continue.)"
	read

	echo -e "\nInstalling Sleepwatcher 2.2 (using the brew command).\nPlease follow the instructions when prompted ...\n(Press ENTER key to continue.)"
	read
	brew install sleepwatcher --quiet
	echo -e "\n\n\nDone.\n(Press ENTER key to continue.)"
	read

	echo -e "\n\nCreating the sleep/wakeup script ..."
		mv sleepScript ~/.sleep
		chmod u+x ~/.sleep
		mv wakeupScript ~/.wakeup
		chmod u+x ~/.wakeup
	echo -e "Done.\n(Press ENTER key to continue.)"
	read

	echo "\nCopying *.plist file to ~/Library/LaunchAgents ..."
	cp /usr/local/Cellar/sleepwatcher/2.2/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist ~/Library/LaunchAgents
	echo -e "Done.\n(Press ENTER key to continue.)"
	read

	echo "\nStarting PleaseSleep"
	launchctl load ~/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
	echo -e "Done.\n(Press ENTER key to continue.)"
	read

	echo -e "\n\n-------------------------------------------------------------------\n\n\nPath to wake script: ~/.wakeup\nPath to sleep script: ~/.sleep\nPath to logging file: /tmp/sleep.log\n\nNote that WiFi will only turn on 5 seconds AFTER your Mac has been waked\n\n-------------------------------------------------------------------\n\n\n\nIF NO ERRORS WERE FOUND, THEN INSTALLATION IS COMPLETE.\n\n\nYour lovely Mac will sleep like a boss now!\n\n\n\n"
fi
